name: GitHub Actions with Cache
on: [push]
jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          #path: ${{ github.repository }}

      - name: List 1
        run: |
          ls -all ${{ github.workspace }}
          touch ${{ github.workspace }}/algo.txt
          tree -L 3 -a
          echo "-----"
          echo "github: ${{ toJSON(github) }}"
          echo "-----"

      - name: Code Cacheing
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/**
          #path: ${{ github.workspace }}/${{ github.repository }}
          key: ${{ github.sha }}
          #restore-keys: ${{ github.event.pull_request.head.sha }}

#      - name: List 2
#        run: |
#          ls ${{ github.workspace }}

  download-from-cache:
    runs-on: ubuntu-latest
    needs: [ clone-repo ]
    #defaults:
    #  run:
    #    working-directory: ${{ github.workspace }}/${{ github.repository }}
    steps:
      - name: Code Cacheing
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/**
          key: ${{ github.sha }}

      #- name: List 2
      #  run: |
      #    mv ${{ github.workspace }}/${{ github.repository }}/* ${{ github.workspace }}
      #    pwd
      #    tree -L 3

      - name: List 3
        run: |
          pwd
          ls -all ${{ github.workspace }}
          tree -L 3 -a


#  download-from-cache-2:
#    runs-on: ubuntu-latest
#    needs: [ download-from-cache ]
    #defaults:
    #  run:
    #    working-directory: ${{ github.workspace }}/${{ github.repository }}
#    steps:
#      - name: Code Cacheing
#        uses: actions/cache@v2
#        with:
#          path: ${{ github.workspace }}/${{ github.repository }}
#          key: ${{ github.sha }}
#
#      - name: List 2
#        run: |
#          mv ${{ github.workspace }}/${{ github.repository }}/* ${{ github.workspace }}
#          pwd
#          tree -L 3
#
#      - name: List 3
#        working-directory: ${{ github.workspace }}/${{ github.repository }}
#        run: |
#          pwd
#          tree -L 3
